#!/bin/zsh

if [ x"$HOME" = x ] ; then
    export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
    export HOSTNAME=$(hostname)
fi

#export MANWIDTH=80

if [ $UID -eq 0 ]; then
    PATH=~root/bin:$PATH
else
    export PATH="${HOME}/bin:${PATH}"
fi

PATH="$PATH:/bin:/usr/bin:/usr/local/bin"
PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
PATH="$PATH:/usr/X11R6/bin:/usr/lib/git-core"
export PATH

# less options
#LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings"
