#!/usr/bin/zsh -f

autoload zmv

alias du="du -hcs"
alias df="df -h"

which lsd > /dev/null 2>&1
if [[ $? -eq 0 || -x "${HOME}/.cargo/bin/lsd" ]]
then
    alias ls="lsd"
else
    which dircolors > /dev/null 2>&1
    if [[ $? -eq 0 ]]
    then
        alias ls="ls --color=auto"
    else
        alias ls="ls -G"
    fi
fi
