#!/bin/zsh

__ZSH_GIT_BRANCH=
__ZSH_GIT_BRANCHCOUNT=
__ZSH_GIT_CLEAN=

zsh_get_git_info() {
    local ref cnt
    local tmpfile l c1 c2 c3 c4
    __ZSH_GIT_BRANCH=
    __ZSH_GIT_BRANCHCOUNT=
    __ZSH_GIT_CLEAN=
    
    ref=$(git symbolic-ref HEAD 2> /dev/null)
    if [[ $ref != "" ]]
    then
	cnt=$(git branch 2> /dev/null | grep -c '.*')
	__ZSH_GIT_BRANCH=$(echo "${ref#refs/heads/}")
	__ZSH_GIT_BRANCHCOUNT=$cnt
	
	git status --porcelain 2> /dev/null > "${tmpfile}"
	l=
	if grep -E '^.M' "${tmpfile}" > /dev/null 2> /dev/null
	then
	    l="M"
	fi
	
	if grep -E '^\?\?' "${tmpfile}" > /dev/null 2> /dev/null
	then
	    l="U${l}"
	fi
	
	if grep -E '^(.U|U.|AA)' "${tmpfile}" > /dev/null 2> /dev/null
	then
	    l="C${l}"
	fi
	
	if grep -E '^[MADRC] ' "${tmpfile}" > /dev/null 2> /dev/null
	then
	    l="A${l}"
	fi
	__ZSH_GIT_CLEAN="${l}"
	rm -f "${tmpfile}"
    fi
}

add-zsh-hook precmd zsh_get_git_info
