#!/bin/zsh

__ZSH_GIT_BRANCH=
__ZSH_GIT_BRANCHCOUNT=
__ZSH_GIT_CLEAN=

zsh_get_git_branch() {
  local ref cnt
  ref=$(git symbolic-ref HEAD 2> /dev/null)
  cnt=$(git branch 2> /dev/null|grep -c -E '*')
  __ZSH_GIT_BRANCH=$(echo "${ref#refs/heads/}")
  __ZSH_GIT_BRANCHCOUNT=$cnt
}

zsh_get_git_clean() {
  local c1 c2 c3 c4 l1 l2 l3 l4 msg
  msg=$(git status 2> /dev/null)
  l1=
  l2=
  l3=
  l4=
  c1=$(echo "$msg" | grep -E '^# Changed but not updated')
  c2=$(echo "$msg" | grep -E '^# Untracked files')
  c3=$(echo "$msg" | grep -E '^#[[:space:]]+unmerged:')
  c4=$(echo "$msg" | grep -E '^# Changes to be committed')
  if [[ "$c1" != "" ]]
  then
    l1=M
  fi
  if [[ "$c2" != "" ]]
  then
    l2=U
  fi
  if [[ "$c3" != "" ]]
  then
    l3=C
  fi
  if [[ "$c4" != "" ]]
  then
    l4=A
  fi
  __ZSH_GIT_CLEAN=${l4}${l1}${l2}${l3}
}

add-zsh-hook precmd zsh_get_git_branch
add-zsh-hook precmd zsh_get_git_clean
