#!/usr/bin/zsh -f

if [[ $NVM_DIR == "" ]]
then
    export NVM_DIR="${HOME}/.nvm"
fi

function nvm() {
    if [[ -s "${NVM_DIR}/nvm.sh" ]]
    then
        unset -f nvm
        . "${NVM_DIR}/nvm.sh"
        nvm "$@"
    else
        echo "nvm not found in ${NVM_DIR}"
        return 1
    fi
}

export PATH="${PATH}:${HOME}/.yarn/bin"

ln -sf "${HOME}/.yarn/bin" "${HOME}/bin/yarn"
if [[ "$NVM_BIN" != "" ]]
then
    ln -sf "$NVM_BIN" "${HOME}/bin/node"
fi
