#!/usr/bin/zsh -f

if [[ $NVM_DIR == "" ]]
then
    export NVM_DIR="${HOME}/.nvm"
fi

function __use_nvm() {
    if [[ -s "${NVM_DIR}/nvm.sh" ]]
    then
        unset -f npm npx nvm node pnpm pnpx yarn
        . "${NVM_DIR}/nvm.sh"
        return 0
    else
        echo "nvm not found in ${NVM_DIR}"
        return 1
    fi
}

function node() {
    __use_nvm && node "$@"
}

function nvm() {
    __use_nvm && nvm "$@"
}

function npm() {
    __use_nvm && npm "$@"
}

function npx() {
    __use_nvm && npx "$@"
}

function yarn() {
    __use_nvm && yarn "$@"
}

function pnpm() {
    __use_nvm && pnpm "$@"
}

function pnpx() {
    __use_nvm && pnpx "$@"
}

export PNPM_HOME="${HOME}/.local/share/pnpm"
export PATH="${PATH}:${HOME}/.yarn/bin:${PNPM_HOME}"

test -d "$PNPM_HOME" && ln -sfT "${PNPM_HOME}" "${HOME}/bin/pnpm"

ln -sfT "${HOME}/.yarn/bin" "${HOME}/bin/yarn"
if [[ "$NVM_BIN" != "" ]]
then
    ln -sfT "$NVM_BIN" "${HOME}/bin/node"
fi

# install pnpm completions if not already installed
which pnpm >/dev/null 2>&1 && {
    test -f "${HOME}/.zfunc/_pnpm" || {
        pnpm completion zsh > "${HOME}/.zfunc/_pnpm"
        source "${HOME}/.zfunc/_pnpm"
    }
}
