#!/usr/bin/zsh -f

if [[ -d "${HOME}/.cargo/bin" ]]
then
    export PATH="${PATH}:${HOME}/.cargo/bin"
    ln -sfT "${HOME}/.cargo/bin" "${HOME}/bin/cargo"
else
    function rustup {
        whence -p rustup >/dev/null && {
            unset -f rustup
            rustup "$@"
            return $?
        }

        (
            source "${HOME}/.zsh.d/lib/_lib.sh"
            _confirm "rustup is not installed. Do you want to install it?" || return 1
            curl -sSL https://sh.rustup.rs | sh || return $?
        ) && {
            unset -f rustup
            export PATH="${PATH}:${HOME}/.cargo/bin"
            ln -sfT "${HOME}/.cargo/bin" "${HOME}/bin/cargo"
        }
    }
fi
