#!/usr/bin/zsh -f

if [[ -x "${HOME}/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js" ]]
then
    alias gsc="${HOME}/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js"
fi
