#!/usr/bin/zsh -f

function rmi_install_tools() {
    (
        source "${HOME}/.zsh.d/lib/_lib.sh"
        local update=false
        _has_arg "-u" "$@" && update=true

        function _check() {
            local tool="$1"
            shift
            local cmd="$1"
            shift
            local repo="$1"
            shift
            local prompt="Install ${cmd}?"
            echo `_set_fgc 14` \
                 "${cmd}" \
                 `_font_reset`

            echo "          " "$@"

            echo -n "          " "Checking ... "
            whence -p "$tool" > /dev/null 2>&1 || {
                echo `_set_fgc 14` \
                     "need '${tool}', skipped." \
                     `_font_reset`
                return 1
            }
            whence -p "$cmd" > /dev/null 2>&1 || {
                echo `_set_fgc 11` \
                     "not found." \
                     `_font_reset`
                _confirm "$prompt"
                return $?
            }

            if [[ $update == true ]]; then
                echo "          " \
                     `_set_fgc 11` \
                     "forced." \
                     `_font_reset`
                return 0
            fi
            echo `_set_fgc 10` \
                installed. \
                `_font_reset`
            return 1
        }

        cat <<EOF
This function installs suggested tools from source.

If any of the tools below are skipped due to missing build tools, you wiil be
prompted to install them (a quoted command like 'go' or 'rustup'). You might also
need build tools like make, gcc, etc. (can be installed in your distro's package
manager) to make rustup work.

If you don't want to install from source, reach to the repo for instructions about
how to install pre-built binaries (like downloading from releases page or using
a package manager).

You can also use the -u option to update tools that are already installed.

EOF

        _check "go" "gum" \
               "https://github.com/charmbracelet/gum" \
               "fancy CLI UI toolset like confirm, select and more" \
            && go install github.com/charmbracelet/gum@latest
        _check "rustup" "bat" \
               "https://github.com/sharkdp/bat" \
               "cat clone with syntax highlighting and Git integration" \
            && cargo install bat
        _check "rustup" "lsd" \
               "https://github.com/lsd-rs/lsd" \
               "ls clone with colors and icons (need special font)" \
            && cargo install lsd
        _check "rustup" "starship" \
               "https://github.com/starship/starship" \
               "modern tool for managing your shell prompt" \
            && cargo install starship
        _check "rustup" "ripgrep" \
               "https://github.com/BurntSushi/ripgrep" \
               "fast search tool like grep, but with more features" \
            && cargo install ripgrep
        _check "rustup" "fd" \
               "https://github.com/sharkdp/fd" \
               "fast and user-friendly alternative to find" \
            && cargo install fd-find
        _check "rustup" "jyt" \
               "https://github.com/ken-matsui/jyt" \
               "convert between JSON, TOML and YAML" \
            && cargo install jyt
    )
}
