#!/usr/bin/zsh -f

which xclip > /dev/null 2>&1
if [[ $? == 0 ]]
then
  alias copy="xclip -selection clipboard"
else
  which xsel > /dev/null 2>&1
  if [[ $? == 0 ]]
  then
    alias copy="xsel -i -b"
  fi
fi

# use gui prompt for gui environment
_is_gui
if [[ $? == 0 && -f /usr/bin/ssh-askpass ]]
then
    export SUDO_ASKPASS=/usr/bin/ssh-askpass
    alias sudo="/usr/bin/sudo -A"

    export SSH_ASKPASS=/usr/bin/ssh-askpass
fi
